export const EMPTY_PRODUCT = {
  name: "",
  category_id: undefined,
  sub_category_id: undefined,
  brand_id: undefined,
  tags: [],
  short_description: "",
  description: "",
  is_hot_deal: false,
  is_new_arrival: false,
  is_featured: false,
  is_best_selling: false,
  is_flash_deal: false,
  flash_deal_start_date: null,
  flash_deal_end_date: null,
  image: null,
  images: [],
  pricing: [
    {
      country_id: undefined,
      price: undefined,
      discount_value: undefined,
      stock: undefined,
      variants_enabled: false,
      use_default_pricing: false,
      options: [],
      variants: [],
    },
  ],
};
